#include <stdio.h>

//#include "InterviewQuestions/03_FindInPartiallySortedMatrix/FindInPartiallySortedMatrix.h"
//#include "InterviewQuestions/04_ReplaceBlank/ReplaceBlank.h"
//#include "InterviewQuestions/05_PrintListInReversedOrder/PrintListInReversedOrder.h"
//#include "InterviewQuestions/06_ConstructBinaryTree/ConstructBinaryTree.h"
//#include "InterviewQuestions/07_QueueWithTwoStacks/QueueWithTwoStacks.h"
//#include "InterviewQuestions/08_MinNumberInRotatedArray/MinNumberInRotatedArray.h"
//#include "InterviewQuestions/09_Fibonacci/Fibonacci.h"
//#include "InterviewQuestions/10_NumberOf1InBinary/NumberOf1InBinary.h"
//#include "InterviewQuestions/11_Power/Power.h"
//#include "InterviewQuestions/12_Print1ToMaxOfNDigits/Print1ToMaxOfNDigits.h"
//#include "InterviewQuestions/13_DeleteNodeInList/DeleteNodeInList.h"
//#include "InterviewQuestions/14_ReorderArray/ReorderArray.h"
//#include "InterviewQuestions/15_KthNodeFromEnd/KthNodeFromEnd.h"
//#include "InterviewQuestions/16_ReverseList/ReverseList.h"
//#include "InterviewQuestions/17_MergeSortedLists/MergeSortedLists.h"
//#include "InterviewQuestions/18_SubstructureInTree/SubstructureInTree.h"
//#include "InterviewQuestions/19_MirrorOfBinaryTree/MirrorOfBinaryTree.h"
//#include "InterviewQuestions/20_PrintMatrix/PrintMatrix.h"
//#include "InterviewQuestions/21_MinInStack/MinInStack.h"
//#include "InterviewQuestions/22_StackPushPopOrder/StackPushPopOrder.h"
//#include "InterviewQuestions/23_PrintTreeFromTopToBottom/PrintTreeFromTopToBottom.h"
//#include "InterviewQuestions/24_SquenceOfBST/SquenceOfBST.h"
//#include "InterviewQuestions/25_PathInTree/PathInTree.h"
//#include "InterviewQuestions/26_CopyComplextList/CopyComplextList.h"
//#include "InterviewQuestions/27_ConvertBinarySearchTree/ConvertBinarySearchTree.h"
//#include "InterviewQuestions/28_StringPermutation/StringPermutation.h"
//#include "InterviewQuestions/29_MoreThanHalfNumber/MoreThanHalfNumber.h"
//#include "InterviewQuestions/30_KLeastNumbers/KLeastNumbers.h"
//#include "InterviewQuestions/31_GreatestSumOfSubarrays/GreatestSumOfSubarrays.h"
//#include "InterviewQuestions/32_NumberOf1/NumberOf1.h"
//#include "InterviewQuestions/33_SortArrayForMinNumber/SortArrayForMinNumber.h"
//#include "InterviewQuestions/34_UglyNumber/UglyNumber.h"
//#include "InterviewQuestions/35_FirstNotRepeatingChar/FirstNotRepeatingChar.h"
//#include "InterviewQuestions/36_InversePairs/InversePairs.h"
//#include "InterviewQuestions/37_FirstCommandNodesInLists/FirstCommandNodesInLists.h"
//#include "InterviewQuestions/38_NumberOfK/NumberOfK.h"
//#include "InterviewQuestions/39_1_TreeDepth/TreeDepth.h"
//#include "InterviewQuestions/39_2_BalancedBinaryTree/BalancedBinaryTree.h"
//#include "InterviewQuestions/40_NumbersAppearOnce/NumbersAppearOnce.h"
//#include "InterviewQuestions/41_1_TwoNumbersWithSum/TwoNumbersWithSum.h"
//#include "InterviewQuestions/41_2_ContinuesSquenceWithSum/ContinuesSquenceWithSum.h"
//#include "InterviewQuestions/42_1_ReverseWordsInSentence/ReverseWordsInSentence.h"
//#include "InterviewQuestions/42_2_LeftRotateString/LeftRotateString.h"
//#include "InterviewQuestions/43_DicesProbability/DicesProbability.h"
//#include "InterviewQuestions/44_ContinousCards/ContinousCards.h"
//#include "InterviewQuestions/45_LastNumberInCircle/LastNumberInCircle.h"
//#include "InterviewQuestions/46_Accumulate/Accumulate.h"
//#include "InterviewQuestions/47_AddTwoNumbers/AddTwoNumbers.h"
//#include "InterviewQuestions/49_StringToInt/StringToInt.h"
#include "InterviewQuestions/50_CommonParentInTree/CommonParentInTree.h"

int main() {

//    Test_3_FindInPartiallySortedMatrix();
//    Test_4_ReplaceBlank();
//    Test_5_PrintListReversed();
//    Test_6_ConstructBinaryTree();
//    Test_7_QueueWithTwoStacks();
//    Test_8_MinNumberInRotatedArray();
//    Test_9_Fibonacci();
//    Test_10_NumberOf1InBinary();
//    Test_11_Power();
//    Test_12_Print1ToMaxOfNDigits();
//    Test_13_DeleteNodeInList();
//    Test_14_ReorderArray();
//    Test_15_KthNodeFromEnd();
//    Test_16_ReverseList();
//    Test_17_MergeSortedLists();
//    Test_18_SubstructureInTree();
//    Test_19_MirrorOfBinaryTree();
//    Test_20_PrintMatrix();
//    Test_21_MinInStack();
//    Test_22_StackPushPopOrder();
//    Test_23_PrintTreeFromTopToBottom();
//    Test_24_SquenceOfBST();
//    Test_25_PathInTree();
//    Test_26_CopyComplextList();
//    Test_27_ConvertBinarySearchTree();
//    Test_28_StringPermutation();
//    Test_29_MoreThanHalfNumber();
//    Test_30_KLeastNumbers();
//    Test_31_GreatestSumOfSubarrays();
//    Test_32_NumberOf1();
//    Test_33_SortArrayForMinNumber();
//    Test_34_UglyNumber();
//    Test_35_FirstNotRepeatingChar();
//    Test_36_InversePairs();
//    Test_37_FirstCommandNodesInLists();
//    Test_38_NumberOfK();
//    Test_39_1_TreeDepth();
//    Test_39_2_BalancedBinaryTree();
//    Test_40_NumbersAppearOnce();
//    Test_41_1_TwoNumbersWithSum();
//    Test_41_2_ContinuesSquenceWithSum();
//    Test_42_1_ReverseWordsInSentence();
//    Test_42_2_LeftRotateString();
//    Test_43_DicesProbability();
//    Test_44_ContinousCards();
//    Test_45_LastNumberInCircle();
//    Test_46_Accumulate();
//    Test_47_AddTwoNumbers();
//    Test_49_StringToInt();
    Test_50_CommonParentInTree();

    return 0;
}